"""add full text search vector to clauses

Revision ID: 4062d8d1afd0
Revises: f1e3fcefb561
Create Date: 2026-09-30 23:38:08.297834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4062d8d1afd0'
down_revision: Union[str, None] = 'f1e3fcefb561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clauses', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=False))
    op.create_index('ix_clauses_search_vector', 'clauses', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clauses_search_vector', table_name='clauses', postgresql_using='gin')
    op.drop_column('clauses', 'search_vector')
    # ### end Alembic commands ###
