"""add storage key and file size to documents

Revision ID: 8db9c492fd62
Revises: 691c6d650a2d
Create Date: 2026-09-25 09:38:08.521311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db9c492fd62'
down_revision: Union[str, None] = '691c6d650a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_key', sa.String(length=500), nullable=False))
    op.add_column('documents', sa.Column('file_size_bytes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_size_bytes')
    op.drop_column('documents', 'storage_key')
    # ### end Alembic commands ###
