"""record why a document failed to read

Revision ID: 8e85d63f0984
Revises: 9907d446818d
Create Date: 2026-10-06 13:39:22.230789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e85d63f0984'
down_revision: Union[str, None] = '9907d446818d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('failure_reason', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'failure_reason')
    # ### end Alembic commands ###
