"""record when a document's status last changed

Revision ID: 9907d446818d
Revises: bca0ad552f63
Create Date: 2026-10-05 16:01:56.683222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9907d446818d'
down_revision: Union[str, None] = 'bca0ad552f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status_changed_at')
    # ### end Alembic commands ###
