"""store the verified quote and allow not-mentioned key terms

Revision ID: 9bccdb732d04
Revises: 4062d8d1afd0
Create Date: 2026-10-03 10:38:54.287811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bccdb732d04'
down_revision: Union[str, None] = '4062d8d1afd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extractions', sa.Column('quote', sa.Text(), nullable=True))
    op.alter_column('extractions', 'value',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint('uq_extractions_field', 'extractions', ['document_id', 'field_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_extractions_field', 'extractions', type_='unique')
    # Rows with no value are the "not mentioned" markers this migration introduced. Going
    # back to a required value can't represent them, so drop them first or the ALTER fails.
    op.execute("DELETE FROM extractions WHERE value IS NULL")
    op.alter_column('extractions', 'value',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('extractions', 'quote')
    # ### end Alembic commands ###
