"""add checklist answers table

Revision ID: bca0ad552f63
Revises: 9bccdb732d04
Create Date: 2026-10-04 20:04:56.068563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bca0ad552f63'
down_revision: Union[str, None] = '9bccdb732d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=100), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'question_id', name='uq_checklist_answers_question')
    )
    op.create_index(op.f('ix_checklist_answers_document_id'), 'checklist_answers', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checklist_answers_document_id'), table_name='checklist_answers')
    op.drop_table('checklist_answers')
    # ### end Alembic commands ###
