"""add content_type and ocr_confidence to documents

Revision ID: f1e3fcefb561
Revises: 8db9c492fd62
Create Date: 2026-09-29 15:39:59.368521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e3fcefb561'
down_revision: Union[str, None] = '8db9c492fd62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows need a real value for this NOT NULL column; every document ingested
    # before today was a PDF, so that's a safe, honest default. New rows always pass an
    # explicit content_type instead of relying on this.
    op.add_column(
        'documents',
        sa.Column(
            'content_type', sa.String(length=100), nullable=False, server_default='application/pdf'
        ),
    )
    op.alter_column('documents', 'content_type', server_default=None)
    op.add_column('documents', sa.Column('ocr_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'ocr_confidence')
    op.drop_column('documents', 'content_type')
    # ### end Alembic commands ###
